import React, { useLayoutEffect, useRef } from 'react';
import gsap from 'gsap';

const WhyTrust = () => {
    const sectionRef = useRef(null);

    useLayoutEffect(() => {
        const tl = gsap.timeline({
            scrollTrigger: {
                trigger: sectionRef.current,
                start: "top 80%",
            }
        });

        tl.fromTo(".feature-card",
            { y: 30, opacity: 0 },
            { y: 0, opacity: 1, stagger: 0.2, duration: 0.8, ease: "power3.out" }
        );
    }, []);

    const features = [
        {
            title: 'No Contract Data Stored',
            desc: 'Your contract data is never stored. We only process and analyze the data in real-time.',
            icon: (
                <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 24 24"><path d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
            )
        },
        {
            title: 'Severity Scoring',
            desc: 'Simple traffic light system (Red/Yellow/Green) helps you prioritize which clauses need immediate negotiation.',
            icon: (
                <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2c5.52 0 10 4.48 10 10s-4.48 10-10 10S2 17.52 2 12 6.48 2 12 2zm0 18c4.41 0 8-3.59 8-8s-3.59-8-8-8-8 3.59-8 8 3.59 8 8 8zm-1-13h2v6h-2V7zm0 8h2v2h-2v-2z" /></svg>
            )
        },
        {
            title: 'Legal Fixes',
            desc: "Don't just find problems. Get suggested counter-clauses and redlines generated by AI to copy-paste directly.",
            icon: (
                <svg className="w-5 h-5 text-white" fill="currentColor" viewBox="0 0 24 24"><path d="M12.65 10C11.83 7.67 9.61 6 7 6c-3.31 0-6 2.69-6 6s2.69 6 6 6c2.61 0 4.83-1.67 5.65-4h3.35v3h3v-3h2v-3h-8.35zm-5.65 4c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z" /></svg>
            )
        }
    ];

    return (
        <section ref={sectionRef} className="w-full max-w-container mx-auto py-24 px-6 relative z-10">
            {/* Section Header */}
            <div className="text-center mb-16">
                <p className="text-[#7c5cfc] text-[11px] font-bold uppercase tracking-[0.2em] mb-4">Why Legal-GPT</p>
                <h2 className="text-4xl md:text-5xl font-extrabold text-white tracking-tighter mb-4">
                    Built for Trust
                </h2>
                <p className="text-[#999] text-base max-w-xl mx-auto">
                    Enterprise-grade legal analysis powered by advanced LLMs, fine-tuned for contract law.
                </p>
            </div>

            {/* Feature Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
                {features.map((feature, idx) => (
                    <div
                        key={idx}
                        className="feature-card group bg-[#111] border border-[#222] p-8 rounded-2xl hover:border-[#333] hover:scale-[1.02] transition-all duration-300 relative overflow-hidden"
                    >
                        {/* Hover Glow */}
                        <div className="absolute -inset-px bg-gradient-to-b from-white/[0.03] to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500" />

                        <div className="relative z-10">
                            <div className="mb-6 w-10 h-10 rounded-xl bg-[#1a1a1a] border border-[#222] flex items-center justify-center">
                                {feature.icon}
                            </div>
                            <h3 className="text-white text-lg font-bold mb-3 tracking-tight">
                                {feature.title}
                            </h3>
                            <p className="text-[#999] text-sm leading-relaxed">
                                {feature.desc}
                            </p>
                        </div>
                    </div>
                ))}
            </div>
        </section>
    );
};

export default WhyTrust;