import React, { useLayoutEffect, useRef } from 'react';
import gsap from 'gsap';

const WhyTrust = () => {
    const sectionRef = useRef(null);

    useLayoutEffect(() => {
        const tl = gsap.timeline({
            scrollTrigger: {
                trigger: sectionRef.current,
                start: "top 80%",
            }
        });

        tl.fromTo(".feature-card",
            { y: 30, opacity: 0 },
            { y: 0, opacity: 1, stagger: 0.2, duration: 0.8, ease: "power3.out" }
        );
    }, []);

    const features = [
        {
            title: 'No Contract Data Stored',
            desc: 'Your contract data is never stored. We only process and analyze the data in real-time.',
            icon: (
                <div className="bg-emerald-500/10 p-3 rounded-lg border border-emerald-500/20">
                    <svg className="w-6 h-6 text-emerald-400" fill="currentColor" viewBox="0 0 24 24"><path d="M13 10V3L4 14h7v7l9-11h-7z" /></svg>
                </div>
            )

        },
        {
            title: "Severity Scoring",
            desc: "Simple traffic light system (Red/Yellow/Green) helps you prioritize which clauses need immediate negotiation.",
            icon: (
                <div className="bg-amber-500/10 p-3 rounded-lg border border-amber-500/20">
                    <svg className="w-6 h-6 text-amber-400" fill="currentColor" viewBox="0 0 24 24"><path d="M12 2c5.52 0 10 4.48 10 10s-4.48 10-10 10S2 17.52 2 12 6.48 2 12 2zm0 18c4.41 0 8-3.59 8-8s-3.59-8-8-8-8 3.59-8 8 3.59 8 8 8zm-1-13h2v6h-2V7zm0 8h2v2h-2v-2z" /></svg>
                </div>
            )
        },
        {
            title: "Legal Fixes",
            desc: "Don't just find problems. Get suggested counter-clauses and redlines generated by AI to copy-paste directly.",
            icon: (
                <div className="bg-blue-500/10 p-3 rounded-lg border border-blue-500/20">
                    <svg className="w-6 h-6 text-blue-400" fill="currentColor" viewBox="0 0 24 24"><path d="M12.65 10C11.83 7.67 9.61 6 7 6c-3.31 0-6 2.69-6 6s2.69 6 6 6c2.61 0 4.83-1.67 5.65-4h3.35v3h3v-3h2v-3h-8.35zm-5.65 4c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z" /></svg>
                </div>
            )
        }
    ];

    return (
        <section ref={sectionRef} className="w-full max-w-7xl mx-auto py-24 px-6 relative z-10">
            {/* Section Header */}
            <div className="text-center mb-16">
                <h2 className="text-4xl md:text-5xl font-black text-white tracking-tighter uppercase italic mb-4">
                    Why Trust Legal-GPT?
                </h2>
                <p className="text-white/60 text-lg max-w-2xl mx-auto font-medium">
                    Enterprise-grade legal analysis powered by advanced LLMs, fine-tuned for contract law.
                </p>
            </div>

            {/* Feature Grid */}
            <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                {features.map((feature, idx) => (
                    <div
                        key={idx}
                        className="feature-card group bg-black border border-white/10 p-10 rounded-3xl hover:border-white/40 transition-all duration-500 shadow-2xl relative overflow-hidden"
                    >
                        {/* Interactive Hover Glow */}
                        <div className="absolute -inset-px bg-gradient-to-b from-white/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-500"></div>

                        <div className="relative z-10">
                            <div className="mb-6 inline-block">
                                {feature.icon}
                            </div>
                            <h3 className="text-white text-2xl font-black mb-4 tracking-tight uppercase">
                                {feature.title}
                            </h3>
                            <p className="text-white/70 text-base leading-relaxed font-medium">
                                {feature.desc}
                            </p>
                        </div>
                    </div>
                ))}
            </div>
        </section>
    );
};

export default WhyTrust;